---
title: "MainImgSegment"
author: "Daniel"
date: "21 de julio de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r ImagenToMatrix}
source('R/functions.r')

require(magick)    # for Advanced Image-Processing
require(imager)
require(imagerExtra)
require(pixmap)




#require(lubridate)    # for data
#require(ggplot2)      # for plotting
#require(igraph)       # for networks


#imag01 <- magick::image_read('Images/Prueba01.bmp')

#fileImag01 <- system.file('C:/Users/user/Documents/Rscrip2018/ImagSegment/Images/Prueba01.bmp',package='imager')

#imag01 <- load.image('C:/Users/user/Documents/Rscrip2018/ImagSegment/Images/Prueba01.bmp')

#path01 <- "C:/Users/user/Documents/Rscrip2018/ImagSegment/Images"

#imager::load.dir(path01)


#oldDir <- getwd()
#apay <- paste(getwd(), "/Images", sep="")
#setwd(apay)

#acus <- bmp::read.bmp('Prueba01.bmp')

#path01 <- "C:/Users/user/Documents/Python Scripts"

#ade <- imager::load.dir("C:/Users/user/Documents/Python Scripts")

#ade es una lista
# recupero los valores de cada posicion de la lista

#ade$rotunda.jpg[1,2,1:3]

#setwd(oldDir)

#imag02 <- magick::image_read('Images/Prueba02.bmp')
#imag03 <- magick::image_read('Images/Prueba02.jpg')


#plot(imag01)

#pr= pixmap::pixmapGrey(imag03)

#pepea <- as.cimg(imag01)

#pepea

nameImag <- validFileImage()

                     
```